var w_info = {
    "name":"vogrig",
    "title":"andrea vogrig",
    "about":"i'm andrea vogrig, an italian programmer, artist and researcher currently based in the netherlands, den haag."
}

var w_data = [
    {
        "name":"instruments/",
        "type":"page",
        "data":[
            {
                "name":"dµad",
                "type":"page",
                "data":[
                    {
                        "name":"image",
                        "type":"image",
                        "data":{
                            "url":"AudioDH-320x156.jpg",
                            "width":"200",
                            "height":"100"
                        }
                    },
                    {
                        "name":"description",
                        "type":"text"
                    },
                    {
                        "name":"buy",
                        "type":"link",
                        "data":""
                    }
                ]
            },
            {
                "name":"2api",
                "type":"page"
            }
        ]
    },
    {
        "name":"music/",
        "type":"page",
        "data":[
            {
                "name":"bbbq/",
                "type":"page"
            },
            {
                "name":"tweeedo/",
                "type":"page"
            }
        ]
    },
    {
        "name":"projects/",
        "type":"page",
        "data":[
            {
                "name":"▨ modd",
                "type":"link",
                "data":"https://modd.farm/"
            },
            {
                "name":"stereomohamed",
                "type":"link",
                "data":"https://stereomohamed.altervista.org/"
            },
            {
                "name":"audio-dh",
                "type":"link",
                "data":"https://audiodh.nl/"
            },
            {
                "name":"infrsnd",
                "type":"page"
            },
            {
                "name":"oneiricon",
                "type":"page"
            },
            {
                "name":"click-box",
                "type":"page"
            },
            {
                "name":"sface",
                "type":"link",
                "data":"https://github.com/sfacee/sface" 
            },
            {
                "name":"oddpubblications",
                "type":"link",
                "data":"https://oddpublications.com/" 
            },
            {
                "name":"3faders",
                "type":"page"
            },
        ]
    },
    {
        "name":"github/",
        "type":"github",
        "data":"vogrig"
    },
    {
        "name":"fun/",
        "type":"page",
        "data":[
            {
                "name":"nothanks",
                "type":"page"
            }
        ]
    }
];
